### ISSUE TITLE
Верстка экрана Search

### ISSUE THREAD

**Issue by Mikle-04** [vaszol/practicum-android-diploma#39]

**Comment by vaszol** [comment]
Вынес в wiki критерии для Presentation и UI
https://github.com/vaszol/practicum-android-diploma/wiki/%5BEpic-1%5D-%D0%9F%D0%BE%D0%B8%D1%81%D0%BA-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9-%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0-1
