### ISSUE TITLE
Логика экрана фильтрация

### ISSUE THREAD

**Issue by vaszol** [vaszol/practicum-android-diploma#43]
Использовать ru.practicum.android.diploma.presentation.filter.FilterViewModel

- [x] Реализовать логику экранов 23,24,25 макета
- [x] Обработка фильтра "ожидаемая зарплата"
- [x] обработка фильтра "не показывать без зарплаты"
- [x] выполнять чтение и запись выбранных параметров в SharedPreferences

**Comment by Quotmovet** [comment]
Есть баг с количеством найденных вакансий, в задаче #146 скорректирую данный момент
