### ISSUE TITLE
Экран детали вакансии доработки (Задача 1)

### ISSUE THREAD

**Issue by vaszol** [vaszol/practicum-android-diploma#83]
Критерии успешного выполнения задач дипломного проекта
Ссылка на урок: [Спринт 25/25 → Тема 1/1: Дипломный проект → Урок 7/11: Критерии успешного выполнения задач дипломного проекта](https://practicum.yandex.ru/learn/android-developer/courses/8e512d47-6da3-4ab6-8464-aff40d0c0a31/sprints/216643/topics/174a1fab-ce65-4a2f-a606-4f543d30c754/lessons/ec32b28d-4221-4327-9de7-7f6017e11a17/#57f4c0fc-462f-4429-b8fd-5af5f59af49f)

[Epic 2] Детали вакансии
Задача 1

- [x] экран «детали» панель навигации не должна отображатся
- [x] экран «детали» отображается индикатор загрузки.
- [ ] экран «детали» отображается плейсхолдер нет интернета или произошла ошибка.
- [x] экран «детали» экран можно проскролить ниже
- [x] экран «детали» уровень зарплаты «от XX»/«от XX до XX»/«до XX»/«зарплата не указана»
- [x] экран «детали» отображается валюта
- [x] экран «детали» логотип компании/плейсхолдер
- [x] экран «детали» отображается адрес/название региона
- [x] экран «детали» отображается описание вакансии в отформатированном виде согласно HTML-тегам в тексте описания
- [x] экран «детали» не/отображается раздел «Ключевые навыки»

**Comment by Basalygina** [comment]
В PR по этой ветке попали сразу несколько задач, т.к. во время работы с избранным, экран деталей вакансии еще не был готов и мне понадобились заглушки. В процессе работы заглушки я заменила на нормальный код, а ветку отдельную создавать уже не стала. Ошибку поняла
